<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Aggregates\" />
    <Folder Include="BuildingBlocks\" />
    <Folder Include="Entities\" />
    <Folder Include="Events\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Repositories\" />
    <Folder Include="Rules\" />
    <Folder Include="Types\" />
    <Folder Include="ValueObjects\" />
  </ItemGroup>

</Project>
