<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CompanyService.Application\CompanyService.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

</Project>
