<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CompanyService.Core\CompanyService.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Convey" Version="0.6.522" />
    <PackageReference Include="Convey.CQRS.Commands" Version="0.6.522" />
    <PackageReference Include="Convey.CQRS.Events" Version="0.6.522" />
    <PackageReference Include="Convey.CQRS.Queries" Version="0.6.522" />

  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\Handlers\" />
    <Folder Include="Commands\WriteModels\" />
    <Folder Include="Dispatchers\" />
    <Folder Include="DTOs\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Queries\" />
  </ItemGroup>
  
</Project>
